import { z } from 'zod';
export declare const envSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "test", "production"]>>;
    APP_NAME: z.ZodDefault<z.ZodString>;
    APP_URL: z.ZodDefault<z.ZodString>;
    API_URL: z.ZodDefault<z.ZodString>;
    API_PORT: z.ZodDefault<z.ZodNumber>;
    CORS_ORIGINS: z.ZodDefault<z.ZodString>;
    LOG_LEVEL: z.ZodDefault<z.ZodEnum<["debug", "info", "warn", "error"]>>;
    LOG_PRETTY: z.ZodDefault<z.ZodEffects<z.ZodUnion<[z.ZodBoolean, z.ZodString]>, boolean, string | boolean>>;
    DEFAULT_COUNTRY: z.ZodDefault<z.ZodString>;
    DEFAULT_CURRENCY: z.ZodDefault<z.ZodString>;
    DEFAULT_LOCALE: z.ZodDefault<z.ZodString>;
    SUPPORTED_LOCALES: z.ZodDefault<z.ZodString>;
    DEFAULT_TIMEZONE: z.ZodDefault<z.ZodString>;
    DATABASE_URL: z.ZodString;
    DIRECT_URL: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    DATABASE_POOL_MIN: z.ZodDefault<z.ZodNumber>;
    DATABASE_POOL_MAX: z.ZodDefault<z.ZodNumber>;
    DATABASE_SSL: z.ZodDefault<z.ZodEffects<z.ZodUnion<[z.ZodBoolean, z.ZodString]>, boolean, string | boolean>>;
    SUPABASE_URL: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    SUPABASE_ANON_KEY: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    SUPABASE_SERVICE_ROLE_KEY: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    AUTH_SECRET: z.ZodEffects<z.ZodString, string, string>;
    REFRESH_SECRET: z.ZodEffects<z.ZodString, string, string>;
    ACCESS_TOKEN_TTL_MINUTES: z.ZodDefault<z.ZodNumber>;
    SESSION_TTL_DAYS: z.ZodDefault<z.ZodNumber>;
    ARGON2_MEMORY_KIB: z.ZodDefault<z.ZodNumber>;
    ARGON2_TIME_COST: z.ZodDefault<z.ZodNumber>;
    ARGON2_PARALLELISM: z.ZodDefault<z.ZodNumber>;
    OTP_LENGTH: z.ZodDefault<z.ZodNumber>;
    OTP_TTL_SECONDS: z.ZodDefault<z.ZodNumber>;
    MAX_LOGIN_ATTEMPTS: z.ZodDefault<z.ZodNumber>;
    LOCKOUT_MINUTES: z.ZodDefault<z.ZodNumber>;
    REDIS_URL: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    REDIS_TLS: z.ZodDefault<z.ZodEffects<z.ZodUnion<[z.ZodBoolean, z.ZodString]>, boolean, string | boolean>>;
    CACHE_TTL_SECONDS: z.ZodDefault<z.ZodNumber>;
    STORAGE_DRIVER: z.ZodDefault<z.ZodEnum<["local", "s3"]>>;
    S3_ENDPOINT: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    S3_REGION: z.ZodDefault<z.ZodString>;
    S3_BUCKET: z.ZodDefault<z.ZodString>;
    S3_ACCESS_KEY_ID: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    S3_SECRET_ACCESS_KEY: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    S3_FORCE_PATH_STYLE: z.ZodDefault<z.ZodEffects<z.ZodUnion<[z.ZodBoolean, z.ZodString]>, boolean, string | boolean>>;
    S3_SIGNED_URL_TTL_SECONDS: z.ZodDefault<z.ZodNumber>;
    PAYMENT_PROVIDER: z.ZodDefault<z.ZodString>;
    PAYMENT_WEBHOOK_SECRET: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    PAYMENT_SANDBOX: z.ZodDefault<z.ZodEffects<z.ZodUnion<[z.ZodBoolean, z.ZodString]>, boolean, string | boolean>>;
    CMI_MERCHANT_ID: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    CMI_STORE_KEY: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    CMI_API_KEY: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    STRIPE_SECRET_KEY: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    STRIPE_WEBHOOK_SECRET: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    PAYPAL_CLIENT_ID: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    PAYPAL_CLIENT_SECRET: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    EMAIL_PROVIDER: z.ZodDefault<z.ZodString>;
    EMAIL_FROM: z.ZodDefault<z.ZodString>;
    SMTP_HOST: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    SMTP_PORT: z.ZodDefault<z.ZodNumber>;
    SMTP_USER: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    SMTP_PASSWORD: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    RESEND_API_KEY: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    SMS_PROVIDER: z.ZodDefault<z.ZodString>;
    SMS_SENDER: z.ZodDefault<z.ZodString>;
    TWILIO_ACCOUNT_SID: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    TWILIO_AUTH_TOKEN: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    TWILIO_FROM_NUMBER: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    PUSH_PROVIDER: z.ZodDefault<z.ZodString>;
    FCM_PROJECT_ID: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    FCM_CLIENT_EMAIL: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    FCM_PRIVATE_KEY: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    MAP_PROVIDER: z.ZodDefault<z.ZodString>;
    MAP_API_KEY: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    MAP_DEFAULT_CENTER_LAT: z.ZodDefault<z.ZodNumber>;
    MAP_DEFAULT_CENTER_LNG: z.ZodDefault<z.ZodNumber>;
    VERIFY_PROVIDER: z.ZodDefault<z.ZodString>;
    VERIFY_API_KEY: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    AI_ENABLED: z.ZodDefault<z.ZodEffects<z.ZodUnion<[z.ZodBoolean, z.ZodString]>, boolean, string | boolean>>;
    AI_PROVIDER: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    AI_API_KEY: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    DEMO_MODE: z.ZodDefault<z.ZodEffects<z.ZodUnion<[z.ZodBoolean, z.ZodString]>, boolean, string | boolean>>;
    FEATURE_FLAGS: z.ZodDefault<z.ZodString>;
    SENTRY_DSN: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    OTEL_ENABLED: z.ZodDefault<z.ZodEffects<z.ZodUnion<[z.ZodBoolean, z.ZodString]>, boolean, string | boolean>>;
    RATE_LIMIT_ENABLED: z.ZodDefault<z.ZodEffects<z.ZodUnion<[z.ZodBoolean, z.ZodString]>, boolean, string | boolean>>;
    RATE_LIMIT_WINDOW_SECONDS: z.ZodDefault<z.ZodNumber>;
    RATE_LIMIT_API_PER_WINDOW: z.ZodDefault<z.ZodNumber>;
    RATE_LIMIT_AUTH_PER_WINDOW: z.ZodDefault<z.ZodNumber>;
    RATE_LIMIT_OTP_PER_WINDOW: z.ZodDefault<z.ZodNumber>;
    RATE_LIMIT_OFFERS_PER_WINDOW: z.ZodDefault<z.ZodNumber>;
    SEED_DEV_USERS: z.ZodDefault<z.ZodEffects<z.ZodUnion<[z.ZodBoolean, z.ZodString]>, boolean, string | boolean>>;
    SEED_DEV_PASSWORD: z.ZodDefault<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "test" | "production";
    APP_NAME: string;
    APP_URL: string;
    API_URL: string;
    API_PORT: number;
    CORS_ORIGINS: string;
    LOG_LEVEL: "debug" | "info" | "warn" | "error";
    LOG_PRETTY: boolean;
    DEFAULT_COUNTRY: string;
    DEFAULT_CURRENCY: string;
    DEFAULT_LOCALE: string;
    SUPPORTED_LOCALES: string;
    DEFAULT_TIMEZONE: string;
    DATABASE_URL: string;
    DIRECT_URL: string;
    DATABASE_POOL_MIN: number;
    DATABASE_POOL_MAX: number;
    DATABASE_SSL: boolean;
    SUPABASE_URL: string;
    SUPABASE_ANON_KEY: string;
    SUPABASE_SERVICE_ROLE_KEY: string;
    AUTH_SECRET: string;
    REFRESH_SECRET: string;
    ACCESS_TOKEN_TTL_MINUTES: number;
    SESSION_TTL_DAYS: number;
    ARGON2_MEMORY_KIB: number;
    ARGON2_TIME_COST: number;
    ARGON2_PARALLELISM: number;
    OTP_LENGTH: number;
    OTP_TTL_SECONDS: number;
    MAX_LOGIN_ATTEMPTS: number;
    LOCKOUT_MINUTES: number;
    REDIS_URL: string;
    REDIS_TLS: boolean;
    CACHE_TTL_SECONDS: number;
    STORAGE_DRIVER: "local" | "s3";
    S3_ENDPOINT: string;
    S3_REGION: string;
    S3_BUCKET: string;
    S3_ACCESS_KEY_ID: string;
    S3_SECRET_ACCESS_KEY: string;
    S3_FORCE_PATH_STYLE: boolean;
    S3_SIGNED_URL_TTL_SECONDS: number;
    PAYMENT_PROVIDER: string;
    PAYMENT_WEBHOOK_SECRET: string;
    PAYMENT_SANDBOX: boolean;
    CMI_MERCHANT_ID: string;
    CMI_STORE_KEY: string;
    CMI_API_KEY: string;
    STRIPE_SECRET_KEY: string;
    STRIPE_WEBHOOK_SECRET: string;
    PAYPAL_CLIENT_ID: string;
    PAYPAL_CLIENT_SECRET: string;
    EMAIL_PROVIDER: string;
    EMAIL_FROM: string;
    SMTP_HOST: string;
    SMTP_PORT: number;
    SMTP_USER: string;
    SMTP_PASSWORD: string;
    RESEND_API_KEY: string;
    SMS_PROVIDER: string;
    SMS_SENDER: string;
    TWILIO_ACCOUNT_SID: string;
    TWILIO_AUTH_TOKEN: string;
    TWILIO_FROM_NUMBER: string;
    PUSH_PROVIDER: string;
    FCM_PROJECT_ID: string;
    FCM_CLIENT_EMAIL: string;
    FCM_PRIVATE_KEY: string;
    MAP_PROVIDER: string;
    MAP_API_KEY: string;
    MAP_DEFAULT_CENTER_LAT: number;
    MAP_DEFAULT_CENTER_LNG: number;
    VERIFY_PROVIDER: string;
    VERIFY_API_KEY: string;
    AI_ENABLED: boolean;
    AI_PROVIDER: string;
    AI_API_KEY: string;
    DEMO_MODE: boolean;
    FEATURE_FLAGS: string;
    SENTRY_DSN: string;
    OTEL_ENABLED: boolean;
    RATE_LIMIT_ENABLED: boolean;
    RATE_LIMIT_WINDOW_SECONDS: number;
    RATE_LIMIT_API_PER_WINDOW: number;
    RATE_LIMIT_AUTH_PER_WINDOW: number;
    RATE_LIMIT_OTP_PER_WINDOW: number;
    RATE_LIMIT_OFFERS_PER_WINDOW: number;
    SEED_DEV_USERS: boolean;
    SEED_DEV_PASSWORD: string;
}, {
    DATABASE_URL: string;
    AUTH_SECRET: string;
    REFRESH_SECRET: string;
    NODE_ENV?: "development" | "test" | "production" | undefined;
    APP_NAME?: string | undefined;
    APP_URL?: string | undefined;
    API_URL?: string | undefined;
    API_PORT?: number | undefined;
    CORS_ORIGINS?: string | undefined;
    LOG_LEVEL?: "debug" | "info" | "warn" | "error" | undefined;
    LOG_PRETTY?: string | boolean | undefined;
    DEFAULT_COUNTRY?: string | undefined;
    DEFAULT_CURRENCY?: string | undefined;
    DEFAULT_LOCALE?: string | undefined;
    SUPPORTED_LOCALES?: string | undefined;
    DEFAULT_TIMEZONE?: string | undefined;
    DIRECT_URL?: string | undefined;
    DATABASE_POOL_MIN?: number | undefined;
    DATABASE_POOL_MAX?: number | undefined;
    DATABASE_SSL?: string | boolean | undefined;
    SUPABASE_URL?: string | undefined;
    SUPABASE_ANON_KEY?: string | undefined;
    SUPABASE_SERVICE_ROLE_KEY?: string | undefined;
    ACCESS_TOKEN_TTL_MINUTES?: number | undefined;
    SESSION_TTL_DAYS?: number | undefined;
    ARGON2_MEMORY_KIB?: number | undefined;
    ARGON2_TIME_COST?: number | undefined;
    ARGON2_PARALLELISM?: number | undefined;
    OTP_LENGTH?: number | undefined;
    OTP_TTL_SECONDS?: number | undefined;
    MAX_LOGIN_ATTEMPTS?: number | undefined;
    LOCKOUT_MINUTES?: number | undefined;
    REDIS_URL?: string | undefined;
    REDIS_TLS?: string | boolean | undefined;
    CACHE_TTL_SECONDS?: number | undefined;
    STORAGE_DRIVER?: "local" | "s3" | undefined;
    S3_ENDPOINT?: string | undefined;
    S3_REGION?: string | undefined;
    S3_BUCKET?: string | undefined;
    S3_ACCESS_KEY_ID?: string | undefined;
    S3_SECRET_ACCESS_KEY?: string | undefined;
    S3_FORCE_PATH_STYLE?: string | boolean | undefined;
    S3_SIGNED_URL_TTL_SECONDS?: number | undefined;
    PAYMENT_PROVIDER?: string | undefined;
    PAYMENT_WEBHOOK_SECRET?: string | undefined;
    PAYMENT_SANDBOX?: string | boolean | undefined;
    CMI_MERCHANT_ID?: string | undefined;
    CMI_STORE_KEY?: string | undefined;
    CMI_API_KEY?: string | undefined;
    STRIPE_SECRET_KEY?: string | undefined;
    STRIPE_WEBHOOK_SECRET?: string | undefined;
    PAYPAL_CLIENT_ID?: string | undefined;
    PAYPAL_CLIENT_SECRET?: string | undefined;
    EMAIL_PROVIDER?: string | undefined;
    EMAIL_FROM?: string | undefined;
    SMTP_HOST?: string | undefined;
    SMTP_PORT?: number | undefined;
    SMTP_USER?: string | undefined;
    SMTP_PASSWORD?: string | undefined;
    RESEND_API_KEY?: string | undefined;
    SMS_PROVIDER?: string | undefined;
    SMS_SENDER?: string | undefined;
    TWILIO_ACCOUNT_SID?: string | undefined;
    TWILIO_AUTH_TOKEN?: string | undefined;
    TWILIO_FROM_NUMBER?: string | undefined;
    PUSH_PROVIDER?: string | undefined;
    FCM_PROJECT_ID?: string | undefined;
    FCM_CLIENT_EMAIL?: string | undefined;
    FCM_PRIVATE_KEY?: string | undefined;
    MAP_PROVIDER?: string | undefined;
    MAP_API_KEY?: string | undefined;
    MAP_DEFAULT_CENTER_LAT?: number | undefined;
    MAP_DEFAULT_CENTER_LNG?: number | undefined;
    VERIFY_PROVIDER?: string | undefined;
    VERIFY_API_KEY?: string | undefined;
    AI_ENABLED?: string | boolean | undefined;
    AI_PROVIDER?: string | undefined;
    AI_API_KEY?: string | undefined;
    DEMO_MODE?: string | boolean | undefined;
    FEATURE_FLAGS?: string | undefined;
    SENTRY_DSN?: string | undefined;
    OTEL_ENABLED?: string | boolean | undefined;
    RATE_LIMIT_ENABLED?: string | boolean | undefined;
    RATE_LIMIT_WINDOW_SECONDS?: number | undefined;
    RATE_LIMIT_API_PER_WINDOW?: number | undefined;
    RATE_LIMIT_AUTH_PER_WINDOW?: number | undefined;
    RATE_LIMIT_OTP_PER_WINDOW?: number | undefined;
    RATE_LIMIT_OFFERS_PER_WINDOW?: number | undefined;
    SEED_DEV_USERS?: string | boolean | undefined;
    SEED_DEV_PASSWORD?: string | undefined;
}>;
export type Env = z.infer<typeof envSchema>;
export interface EnvValidationResult {
    ok: boolean;
    env?: Env;
    errors: string[];
}
/**
 * Validate an environment map. In production the auth/refresh secrets must
 * be real; in development we substitute deterministic dev-only values so a
 * fresh clone boots without ceremony, while still never shipping them.
 */
export declare function validateEnv(raw: Record<string, string | undefined>): EnvValidationResult;
export declare function getEnv(): Env;
export declare const env: Env;
//# sourceMappingURL=env.d.ts.map