process.env.NODE_ENV='test';
process.env.DATABASE_URL='postgresql://postgres@127.0.0.1:55432/bidly_test';
process.env.DATABASE_SSL='false';
process.env.AUTH_SECRET='test-access-secret-that-is-long-enough-000000000000';
process.env.REFRESH_SECRET='test-refresh-secret-that-is-different-0000000000';
process.env.RATE_LIMIT_ENABLED='false';
const captured=[];
const { buildApp } = await import('/mnt/workspace/071847ad-8ab0-4cb6-adfa-06e6d99215e7/apps/api/dist/app.js');
const app = await buildApp({ notifier: { sendEmail: async(t,s,b)=>captured.push(b), sendSms: async(t,b)=>captured.push(b) } });
const email=`probe-${Date.now()}@example.com`;
await app.inject({method:'POST',url:'/api/v1/register',payload:{email,password:'Str0ngPass1',fullName:'T',role:'PROVIDER'}});
const code=[...captured].reverse().map(b=>(b.match(/(\d{4,8})/)||[])[1]).find(Boolean);
await app.inject({method:'POST',url:'/api/v1/verify-email',payload:{email,code}});
const login=await app.inject({method:'POST',url:'/api/v1/login',payload:{identifier:email,password:'Str0ngPass1'}});
const tok=login.json().data.accessToken;
const res=await app.inject({method:'POST',url:'/api/v1/providers',headers:{authorization:`Bearer ${tok}`},payload:{displayName:'Probe Provider',serviceRadiusKm:20}});
console.log('status',res.statusCode);
console.log(res.body.slice(0,800));
await app.close();
